# Dockerfile.base
FROM ruby:latest
LABEL rails_cookies_everywhere=ruby:latest

# Install dependencies
RUN apt-get update -qq && apt-get install -y nodejs git

# Clone the Rails repository
RUN git clone https://github.com/rails/rails.git /rails

# Set the working directory
WORKDIR /rails
